### PR TITLE
DEV: assigns flags to user on create and rake task to assign otheres

### PR DESCRIPTION
**Pull request by Ahmedgagan**

### CODE REVIEW

**Comment by Ebsy** [comment]
Wow. This is amazing! Can I ask @merefield to also take a look?

**Comment by Ebsy** [comment]
@Ahmedgagan can you give a bit more info on what you’ve integrated here?

**Comment by merefield** [comment]
@Ahmedgagan can you please remove all gem files and directories?  Currently this PR is adding 310 files(!) which makes it really hard to review.  These should be completely excluded.  The repo was missing a `.gitignore` file, but I've gone ahead and added that now, perhaps you can pull that into your branch?

**Comment by Ahmedgagan** [comment]
Hi @Ebsy @merefield 
Can we close this PR? I am working on another branch. I'll create another PR in some time?

**Pull request closed without merging**
